Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,16 +16,20 @@ jobs:
       - run: |
           pip install -r requirements.txt
           python manage.py test taskManager
-          
-  release:
-    machine: true                                        # What is this for?
+
+  oast:
+    machine: true
     steps:
       - checkout
-      - run: |
-          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-          docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
-          docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
-          
+
+      - run:
+          command: docker run -v $(pwd):/src --rm hysnsec/safety check -r /src/requirements.txt --json | tee oast-results.json || true
+
+      - store_artifacts:
+          path: oast-results.json
+          destination: safety-artifact
+          when: always
+
   integration:
     docker:
       - image: python:3.6
@@ -34,34 +38,31 @@ jobs:
       - run:
           command: |
             echo "This is an integration step"
-            exit 0
-          when: always                    # Even if the job fails, continue to the next stages
+            exit 1
+          when: on_fail                    # Even if the job fails, continue to the next stages
 
   prod:
     docker:
       - image: python:3.6
     steps:
       - checkout
-      - run: echo "This is a 'deploy' step."
-
-  oast:
-    machine: true
-    steps:
-      - checkout
-
-      - run: docker run -v $(pwd):/src --rm hysnsec/safety check -r /src/requirements.txt --json | tee oast-results.json
-
-      - store_artifacts:
-          path: oast-results.json
-          destination: safety-artifact
-        when: always
+      - run: echo "This is a deploy step"
 
 workflows:
   version: 2
   django:
     jobs:
       - build
-      - test
-      - oast
-      - integration
-      - prod
+      - test:
+          requires:
+            - build
+      - oast:
+          requires:
+            - test
+      - integration:
+          requires:
+            - oast
+      - prod:
+          type: approval
+          requires:
+            - integration
